### ISSUE TITLE
Bug: "Wound rolls of 6" select box AP options cause form submission to fail

### ISSUE THREAD

**Issue by Frostbeard** [toadchild/40kdice#1]
I stumbled upon this while simulating genestealers vs tactical marines.

To reproduce, enter the values as shown in this screenshot:
![image](https://user-images.githubusercontent.com/1134123/60156136-0b845580-97a9-11e9-96f9-60b96fed69c3.png)

Then, change the "Wound rolls of 6" to one of the armor piercing options (seems to happen for all of three of them) and hit "Roll".  You'll get a console error that reads:

>ReferenceError: wound_prob is not defined dice-1551158823.js:453:32
>    do_saves http://40k.ghostlords.com/dice/dice-1551158823.js:453
>    roll_40k http://40k.ghostlords.com/dice/dice-1551158823.js:648
>    onclick http://40k.ghostlords.com/dice/:1

Looks like wound_prob is out of scope for the do_saves function.

**Comment by toadchild** [comment]
Thanks for the bug report!  Looks like I missed something the last time I refactored things.
