### ISSUE TITLE
Saves seem to be capped at 6, can't auto-fail on base 7+ or AP

### ISSUE THREAD

**Issue by Thrax37** [toadchild/40kdice#13]
It seems that the saves can't be entirely ignored even when starting from 7+ or when the armour penetration would bring the value to a number strictly superior to 6+. In every case, the formula seems to consider that damage can be saved as if the defender had a 6+ save.

Here's a screenshot (with auto-hit, auto-wound, 7+ save) :
![image](https://github.com/toadchild/40kdice/assets/6884890/f6dd32d7-44ea-4d6a-beaa-781cf4e0a1a8)

We can see that the expected value after save should still be "1" but it becomes "0.83", as if you had a 1/6 chance to save.

**Comment by toadchild** [comment]
Thanks for the report - you are correct, this is an error. It appears I accidentally introduced it when I refactored hit/wound rolls to have a variable crit target in order to support 40K 10th edition.
