### ISSUE TITLE
Anti-X isn't working and/or devastating wounds

### ISSUE THREAD

**Issue by Calioses** [toadchild/40kdice#16]
I have the data filled out for Drukhari Haywire Blasters shooting into Leman Russ's and the Anti-X and/or devastating wounds isn't being registered as the wound count is way too low. 
![Screenshot 2024-01-28 141308](https://github.com/toadchild/40kdice/assets/55723201/7ab151ad-e11f-4b68-9155-d74d4f3cf9f3)

**Comment by toadchild** [comment]
Can you please include the URL for the roll you made, rather than just a screenshot? Thanks!

**Comment by toadchild** [comment]
Same config as the screenshot: https://40k.ghostlords.com/dice/#attacks=8&bs=4&ap=-1&s=3&d=3&t=11&save=2&wounds=13&wound_crit=4&wound_dev

EV: 6 wounds

With only devastating wounds (not anti-X): https://40k.ghostlords.com/dice/#attacks=8&bs=4&ap=-1&s=3&d=3&t=11&save=2&wounds=13&wound_dev

EV: 4 wounds

With only anti-X 4+ (no devastating wounds): https://40k.ghostlords.com/dice/#attacks=8&bs=4&ap=-1&s=3&d=3&t=11&save=2&wounds=13&wound_crit=4

EV: 4 wounds

With neither devastating wounds nor anti-X: https://40k.ghostlords.com/dice/#attacks=8&bs=4&ap=-1&s=3&d=3&t=11&save=2&wounds=13

EV: 0.67 wounds

**Comment by toadchild** [comment]
I can double check some of the math, but it appears that both devastating wounds and anti-X are individually increasing the number of wounds, and when taken together, are even more potent.

**Comment by toadchild** [comment]
Basic sanity check on the expected value (EV) calculations:

* 8 attacks
* at 4+ BS, 50% hit, so you expect 4 hits
* with anti-x 4+, 50% wound, so you expect 2 wounds
* Mortal wounds bypass all saving throws
* 3 damage each, so expected damage is 6

There doesn't appear to be a bug here, closing this issue.
