### ISSUE TITLE
Add defense "profiles"

### ISSUE THREAD

**Issue by Raphtor** [toadchild/40kdice#19]
It would be nice to allow users to create various defense "profiles" and do the rolls for each for easy comparison. For example, you could see how a particular weapon profile works against a "Tank" profile that has a single model with high wounds/toughness and a low save or a "Swarm" profile with low wounds/toughness, low saves and many models. 

I can implement and make a PR.

**Comment by Raphtor** [comment]
I just realized that UnitCrunch is a thing, but happy to still implement this if desired. Closing for now.

**Comment by toadchild** [comment]
Thanks for the input - I wasn't aware of unitcrunch when I started my tool (I don't actually know if it existed back then), but right now I'm not looking to completely overhaul the design. However, I do still appreciate the input and I'm willing to consider options in the future.

**Comment by toadchild** [comment]
Please feel free to reach out to me via my contact email if you'd like to collaborate on any feature development!
