### ISSUE TITLE
Wrong results when combining lethal and sustained hits when hitting on 6s (overwatch etc)

### ISSUE THREAD

**Issue by Dreyven** [toadchild/40kdice#20]
When you set BS/WS to hitting on 6s while using both lethal and sustained hits all hits automatically become auto wounds regardless of strength vs toughness. This is incorrect as extra hits generated by sustained are not auto wounding.

![grafik](https://github.com/toadchild/40kdice/assets/24802412/8707fcdd-916a-4609-b3b4-01b57ace6601)

![grafik](https://github.com/toadchild/40kdice/assets/24802412/4d4b3dd2-dcf3-43a2-8fd9-d83bd8b4fbbf)

**Comment by toadchild** [comment]
This is a known issue that I need to address. See #12 as the main place I'm tracking this.
