### ISSUE TITLE
Mobile site still uses (non-functional) 8th ed version

### ISSUE THREAD

**Issue by Terrorforge** [toadchild/40kdice#8]
The mobile version of the dice app site (http://40k.ghostlords.com/dice/) uses the 8th edition version still, and it doesn't even work (results just list expected number of attacks)

You can set your phone browser to fetch the desktop version, of course, but not everyone knows that.

**Comment by toadchild** [comment]
I’m not quite sure what you’re intending to report here - there’s no separate mobile version of the page. I serve exactly the same contents to all clients and do not check browser versions. I tested on my own phone just now and everything renders fine.

**Comment by Terrorforge** [comment]
Oh, it was probably just my phone having a cached version of the old page. I'm getting the 10th ed one now, my bad.
